#!/usr/bin/env bash
# Bash script that displays the listening ports:
# which only shows listening sockets
# and also that showss the PID and name of the program to which each socket belongs

netsat -l -p
